apiVersion: v1
kind: Secret
metadata:
  name: api-key-secret
type: Opaquesk
data:
  OPENAI_API_KEY: c2stcHJvai1rRW1wOUdHLW11WG1QUXEtNU5rMnFJUmFQUWxqZTBSaFhFWVdSdng0WVhEbUw0WndrS1RyQkgzQmU1M0pRWWRMSVFNdWlYV2lFX1QzQmxia0ZKUDRweUZNQmJGZDh1UU9jQ1h2bWw0V2xWQ3Z5R2ZmMnFKM0wzV3kyeWhmenRWSDJwaExiREIwLVhMZ2ZUU0FqclNaVDRBYnRWWUE=