apiVersion: v1
kind: Secret
metadata:
  name: api-key-secret
type: Opaque
data:
  OPENAI_API_KEY: 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